---
title: "Lab 9"
author: "Amanda Murphy"
date: "11/10/2021"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

```{r}
library(dplyr)

e1_data <- When_not_choosing_leads_to_not_liking_Data %>%
  filter(ExperimentNumber == "1") 


sum_C <- sum(e1_data$`Infant Chose C`)
total_C <- length(e1_data$`Infant Chose C`)

(binomial_p <- pbinom(q = total_C - sum_C,
                      size = total_C, prob = .5,lower.tail = TRUE)*2)

```
#gender

```{r}
library(tidyr)


gender_choice_table <- e1_data %>%
  group_by(Gender, `Infant Chose C`) %>%
  summarize(counts = n()) %>%
  pivot_wider(names_from = c(Gender),
              values_from = counts)

gender_choice_table <- gender_choice_table[,2:3]

(gender_Xsq <- chisq.test(gender_choice_table))

uncorrected_Xsq <-  sum((gender_Xsq$observed-gender_Xsq$expected)^2/gender_Xsq$expected)

#age

age_table <- e1_data %>%
  group_by(AgeMonths, `Infant Chose C`) %>%
  summarize(counts =n()) %>%
  pivot_wider(names_from = c(AgeMonths),
              values_from = counts)

age_table[is.na(age_table)] <- 0
age_table <- as.matrix(age_table[,2:21])
(age_xs <- chisq.test(age_table))
  

```

